FROM debian:trixie

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY dist/eva-1.0.1-cp313-cp313-linux_aarch64.whl /tmp/

RUN pip install --break-system-packages /tmp/eva-1.0.1-cp313-cp313-linux_aarch64.whl

RUN git clone https://github.com/microsoft/EVA.git /eva

RUN pip install --break-system-packages -r /eva/examples/requirements.txt

WORKDIR /eva/examples
CMD ["python3", "image_processing.py"]
