name: Build EVA wheels

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          #- platform: linux-x86_64
          #  runner: ubuntu-24.04
          #  script: docker build --output type=local,dest=./dist - < Dockerfile.linux-build
          #  artifact-path: dist/*.whl
          #- platform: linux-aarch64
          #  runner: ubuntu-24.04-arm
          #  script: docker build --output type=local,dest=./dist - < Dockerfile.linux-build
          #  artifact-path: dist/*.whl
          - platform: macos-arm64
            runner: macos-15
            script: bash build-macos.sh
            artifact-path: /tmp/EVA/dist/*.whl
    steps:
      - uses: actions/checkout@v4

      - name: Build wheel and run tests
        run: ${{ matrix.script }}

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: eva-wheel-${{ matrix.platform }}
          path: ${{ matrix.artifact-path }}
